# This rule is not used by the project kubebackup-manager itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to backup.bizaikube.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebackup-manager
    app.kubernetes.io/managed-by: kustomize
  name: backuprun-viewer-role
rules:
- apiGroups:
  - backup.bizaikube.io
  resources:
  - backupruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.bizaikube.io
  resources:
  - backupruns/status
  verbs:
  - get
